### ISSUE TITLE
Error uploading weight to Garmin Connect: forbidden

### ISSUE THREAD

**Issue by malcolmCZECH** [lswiderski/WebBodyComposition#1]
Hi, new error from Garmin: Error uploading weight to Garmin Connect: Forbidden. Cay you resolve this problem? I am uploading through https://web-body-composition.vercel.app/ Thanks.

**Comment by aabytt** [comment]
Same issue. Tried different browsers with no luck.

**Comment by saint-werner** [comment]
Same problem.  Worked perfectly and then just stopped with this error.

**Comment by lswiderski** [comment]
The GO client for Garmin Connect stopped working (https://github.com/abrander/garmin-connect/issues/26). 

Instead of waiting for a fix I replaced it by my implementation from:
https://github.com/lswiderski/yet-another-garmin-connect-client


It should work now.

**Comment by saint-werner** [comment]
Tried last evening, and gave error popup with "undefined",  and just tested now again with resulting error popup empty.
![IMG_4340](https://github.com/lswiderski/WebBodyComposition/assets/120994256/de3fda11-d25f-4fd4-8490-78b252920b80)
![IMG_4337](https://github.com/lswiderski/WebBodyComposition/assets/120994256/d8ed8b5f-ed2f-4012-a078-13f9c737b7e3)

**Comment by lswiderski** [comment]
@saint-werner Thanks, found a bug with visceral fat and metabolic year. The new API do not accept them as decimal. I will fix it tomorrow. For now as workaround you can remove decimal points in that 2 fields so 9 not 9.71 and 20.

**Comment by lswiderski** [comment]
@saint-werner Fixed
