### ISSUE TITLE
No data update

### ISSUE THREAD

**Issue by bartlomiej85** [lswiderski/WebBodyComposition#2]
Hi, since yesterday data are not updating into Garmin service even that i got information in bluefy 'Success. Uploaded". Tried in Bluefy, Chrome and Safari.

**Comment by lswiderski** [comment]
Hi @bartlomiej85 
Thanks for the report. A small error sneaked into the API. Fix is live and now everything should works correctly.

**Comment by bartlomiej85** [comment]
Hi @lswiderski ,

yep, I can confirm that now works fine! Thanks for quick fix 🍻
