### ISSUE TITLE
Error when sending info to Garmin

### ISSUE THREAD

**Issue by gawlow** [lswiderski/WebBodyComposition#4]
Hey I was trying the app for the first time and got the issue:

![image](https://github.com/lswiderski/WebBodyComposition/assets/40031413/4dec5c35-59e0-426d-9caa-67c48bc2ffd4)

Is it just proxy being too crowded?

**Comment by lswiderski** [comment]
Hi @gawlow
Yes, Garmin API returned Too many requests error. It can usually happen in the mornings. If this happen again I suggest to try later or use new feature with generating only .FIT file with activity and manual upload it in Garmin Connect.
![image](https://github.com/lswiderski/WebBodyComposition/assets/2623594/07a95635-d234-46af-a4a8-c2b3379a5d9e)
