### ISSUE TITLE
Mi Scale 2 Not Detected

### ISSUE THREAD

**Issue by Jorgovan3** [lswiderski/WebBodyComposition#5]
Hello, I tried this on an iphone 12 with Bluefy, but it doesn’t recognize my scale. I have a Mi Scale 2 (not the body composition version). If it should work with this scale too, could tou please advise what to do?

Thanks!

**Comment by lswiderski** [comment]
Hi @Jorgovan3 
Only body composition scale is supported. Basic Mi Scale measure only weight, and it's possible to add weight from Garmin Connect app just with one click. So there is no need for external app for this.

**Comment by Jorgovan3** [comment]
Thanks for your reply! It makes sense. I was used to not do anything manually with Zepp, but that’s life.
